# Generated by Django 5.2 on 2025-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo', '0002_custo_custopolietileno750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custo',
            name='custoBarreira',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Barreira (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoCeluloseVirgem',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Celulose virgem (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoElastico',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Elastico (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoFitaAdesiva',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Fita adesiva (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoGel',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Gel (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoHotMelt',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Hot-Melt (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoPolietileno750',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno 750 (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoPolietileno780',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Polietileno 780 (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoTnt750',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TNT 750 (R$)'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='custoTnt780',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TNT 780 (R$)'),
        ),
    ]
