# Generated by Django 5.2 on 2025-04-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo', '0003_alter_custo_custobarreira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custo',
            name='custoPolietileno162',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno 162 (R$)'),
        ),
        migrations.AddField(
            model_name='custo',
            name='custoTnt162',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TNT 162 (R$)'),
        ),
    ]
