# Generated by Django 5.2 on 2025-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fralda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('identificacao', models.CharField(max_length=100)),
                ('tamanho', models.CharField(max_length=100)),
                ('qtdCeluloseVirgem', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdGel', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdTnt750', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdTnt780', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdFitaAdesiva', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdElastico', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdBarreira', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdPolietileno780', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdHotMelt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qtdPorPacote', models.IntegerField()),
                ('percentPerdas', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precoEmbalagem', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precoFardoEncarte', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percentComissao', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percentImpostos', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percentFrete', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percentMargem', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percentST', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
