# Generated by Django 5.2 on 2025-04-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fralda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fralda',
            old_name='identificacao',
            new_name='identificador',
        ),
    ]
