# Generated by Django 5.2 on 2025-04-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fralda', '0002_rename_identificacao_fralda_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='fralda',
            name='qtdPolietileno750',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
