# Generated by Django 5.2 on 2025-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fralda', '0003_fralda_qtdpolietileno750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fralda',
            name='identificador',
            field=models.CharField(max_length=100, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='percentComissao',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='percentFrete',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Frete (%)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='percentImpostos',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Impostos (%)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='percentMargem',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Margem de contribuição (%)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='percentPerdas',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Perdas (%)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='percentST',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ST (%)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='precoEmbalagem',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Embalagem (R$)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='precoFardoEncarte',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Saco para fardos/Encarte (R$)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdBarreira',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Barreira (m2)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdCeluloseVirgem',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Celulose virgem (Kg)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdElastico',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Elastico (Kg)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdFitaAdesiva',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Fita adesiva (m)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdGel',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Gel (Kg)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdHotMelt',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Hot-Melt (Kg)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdPolietileno750',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno 750 (Kg)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdPolietileno780',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Polietileno 780 (Kg)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdPorPacote',
            field=models.IntegerField(verbose_name='Quantidade de fraldas por pacote'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdTnt750',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TNT 750 (m2)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='qtdTnt780',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TNT 780 (m2)'),
        ),
        migrations.AlterField(
            model_name='fralda',
            name='tamanho',
            field=models.CharField(max_length=100, verbose_name='Tamanho'),
        ),
    ]
