# Generated by Django 5.2 on 2025-04-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fralda', '0005_alter_fralda_modelo_alter_fralda_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='fralda',
            name='qtdPolietileno162',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno 162 (Kg)'),
        ),
        migrations.AddField(
            model_name='fralda',
            name='qtdTnt162',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TNT 162 (m2)'),
        ),
    ]
