# Generated by Django 5.2 on 2025-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fralda', '0006_fralda_qtdpolietileno162_fralda_qtdtnt162'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fralda',
            name='tamanho',
            field=models.CharField(choices=[('XG', 'XG'), ('G', 'G'), ('M', 'M'), ('TAMANHO ÚNICO', 'TAMANHO ÚNICO')], max_length=100, verbose_name='Tamanho'),
        ),
    ]
