# Generated by Django 5.2 on 2025-04-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custo', '0001_initial'),
        ('fralda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo.custo')),
                ('fralda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fralda.fralda')),
            ],
        ),
    ]
