# Generated by Django 5.2 on 2025-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulacao',
            old_name='custo',
            new_name='custoObj',
        ),
        migrations.RenameField(
            model_name='simulacao',
            old_name='fralda',
            new_name='fraldaObj',
        ),
        migrations.AddField(
            model_name='simulacao',
            name='barreiraCUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='celuloseVirgemCUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='elasticoCUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='fitaAdesivaCUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='fraldaCUF',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='fraldaCustoPacote',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='fraldaCustoTotalComPerdas',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='fraldaCustoTotalSemPerdas',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='gelCUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='hotMeltCUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='polietileno750CUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='polietileno780CUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='precoVenda',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='precoVendaST',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='precoVendaUnitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='precoVendaUnitarioST',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='tnt750CUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='tnt780CUT',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
