# Generated by Django 5.2 on 2025-04-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0002_rename_custo_simulacao_custoobj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao',
            name='barreiraCUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='celuloseVirgemCUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='elasticoCUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='fitaAdesivaCUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='fraldaCUF',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='fraldaCustoPacote',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='fraldaCustoTotalComPerdas',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='fraldaCustoTotalSemPerdas',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='gelCUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='hotMeltCUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='polietileno750CUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='polietileno780CUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='precoVenda',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='precoVendaST',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='precoVendaUnitario',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='precoVendaUnitarioST',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='tnt750CUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='tnt780CUT',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
    ]
