# Generated by Django 5.2 on 2025-04-14 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo', '0003_alter_custo_custobarreira_and_more'),
        ('fralda', '0004_alter_fralda_identificador_alter_fralda_modelo_and_more'),
        ('simulacao', '0003_alter_simulacao_barreiracut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao',
            name='custoObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo.custo', verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='fraldaObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fralda.fralda', verbose_name='Fralda'),
        ),
    ]
